### ISSUE TITLE
docker not found on make-image.mk

### ISSUE THREAD

**Issue by edgurgel** [asaaki/elixir-docker-image-packager#4]
I'm using `mix-edip` and everything is running fine till the moment when it runs

`make -f package/make-image.mk`

I get this

```
docker import --change 'CMD trap exit TERM; /app/bin/hello foreground & wait' - myregistry/hello:latest
/bin/sh: docker: not found
```

(It doesn't happen on my machine, just on the CI machine)

I wonder if it's because the make-image.mk does not have this:

`DOCKER = $(shell which docker)`
https://github.com/asaaki/elixir-docker-image-packager/blob/master/Makefile#L10

This is the only difference I can see between the `docker build` call and the `docker import` one.

Any clues? :+1: 

Thanks for this awesome project

**Comment by asaaki** [comment]
Is it possible that the CI machine does not work properly with mounted volumes?

Because what it normally does is following:
- on host level:
  - create the staging image (`make build-stage`)
  - start packaging (`make build-package`)
    - using a privileged docker container (`--privileged`)
    - using volumes to expose the host docker to the staging container

At this point 3 volumes should be mounted into the staging container, 2 related to docker:

```
# Makefile L14-15:
    -v $(DOCKER_SOCK):$(DOCKER_SOCK) \
    -v $(DOCKER):$(DOCKER)
```

Means: the docker executable and the socket are exposed and usable within the staging container, so that we do not have to install docker in the container (and the socket would have to be mounted anyways to save the created image on your host).

I only can guess here, but I think that your CI environment has a different setup for docker and therefore the path for the executable is nothing usual here.

Could you please run a `which docker` on your CI? I'd like to know if the path is something different than `/usr/bin/docker` or `/usr/local/bin/docker`. It might be that I have to fix the path for the staging container.

**Comment by asaaki** [comment]
I have pushed and published an update:

EDIP now uses a fixed path for internal docker executable (`/usr/bin/docker`), no matter what the path on the host is.

Please update _mix-edip_ in your project (`mix deps.update edip`), it should be on version 0.2.2 then.
This will use the updated EDIP tool, which hopefully works for your CI, too.

**Comment by asaaki** [comment]
And if you test it locally in an existing project, you might want to run `mix edip -f` to force a fresh download of the EDIP tool.

**Comment by edgurgel** [comment]
Thanks for the explanation! 

I tried with this new version but it didn't work :/

The CI I'm using is [drone](https://github.com/drone/drone) and it runs on top of a container that you can specify. It should be able to do everything needed. I will try to run the CI locally so I can somehow debug.

It surely has docker as I'm using an ubuntu image with elixir, docker,git and socat installed. And it works perfectly until the docker import call. The tarball is generated! The docker build just works. 

Because of this whole docker/docker/docker thing I had to specify the host like this `DOCKER_HOST=tcp://$(MY_HOST):2375 MIX_ENV=prod mix edip`. 

I wonder why docker would be not found in this case as it clearly was available. Do you think it could be related to the SHELL variable or something? I'm really just guessing here.

Thanks again for helping with this weird issue :)

**Comment by asaaki** [comment]
I guess I have an idea what's not working. It seems it (drone) uses docker via TCP instead of a Unix socket. Even if this is not the case, the following will still apply.

I had this idea already in the past, but maybe I should revive it again: Instead of nesting the containers it should build the tarball artifact first and create the image on the host level again, so it doesn't need to nest the dockers at all. (I was already afraid that this nesting could lead to troubles.)

**Comment by edgurgel** [comment]
Would this introduce any complication? Cause it seems to be simpler. 

But this TCP/Unix thing would cause to not found the docker executable? That's the weird part :/

**Comment by asaaki** [comment]
Yeah, you're right, a mounted executable should be present anyway.
I would have to replicate your setup I guess.
Do you use drone, the project, or drone.io?
How difficult would it be to have such testing environment?

**Comment by edgurgel** [comment]
I use just the project and not the service. 

It should be simply as installing locally then using an image that has `docker`, `socat` and `git`. Something like:

```
FROM cargosense/elixir

RUN locale-gen en_US.UTF-8 && \
  apt-get -y update && \
  apt-get -y install socat && \
  apt-get clean

# Install docker
ADD https://get.docker.io/ubuntu docker.sh
RUN sh docker.sh
RUN rm -rf docker.sh
ADD https://get.docker.com/builds/Linux/x86_64/docker-1.7.1 /usr/bin/docker
RUN chmod +x /usr/bin/docker
```

(I tried to use the same elixir-dev that edip uses but I had some weird issues. Then I went straight to this base image.)

The .drone.yml would be something like 

```
image: the_custom_image
script:
  - mix local.hex --force && mix local.rebar --force
  - mix edip
```

Then you use the Drone UI to run some hello world Elixir project.

It feels like a lot of configuration TBH :/. I will try to run it locally and report back.

**Comment by edgurgel** [comment]
I have more information! I'm running edip standalone and using `make TARBALL=only`. I get this when doing `ls -lah` on `.edip`:

```
Only tarball created: tarballs/20150807_002543/hello-0.0.1.tar.gz
Create your own docker image with 'docker import' command.
See: <https://docs.docker.com/reference/commandline/import/>
total 32K
drwxr-xr-x 1 root root  168 Aug  7 00:25 .
drwxr-xr-x 1 root root    8 Aug  7 00:25 ..
drwxr-xr-x 1 root root  138 Aug  7 00:25 app
drwxr-xr-x 1 root root   32 Aug  7 00:25 dockerfiles
-rw-r--r-- 1 root root   72 Aug  7 00:25 .dockerignore
drwxr-xr-x 1 root root  138 Aug  7 00:25 .git
-rw-r--r-- 1 root root   35 Aug  7 00:25 .gitignore
-rw-r--r-- 1 root root 1.1K Aug  7 00:25 LICENSE
-rw-r--r-- 1 root root 2.0K Aug  7 00:25 Makefile
drwxr-xr-x 1 root root  112 Aug  7 00:25 package
-rw-r--r-- 1 root root 8.8K Aug  7 00:25 README.md
drwxr-xr-x 1 root root   76 Aug  7 00:25 tools
-rw-r--r-- 1 root root    6 Aug  7 00:25 VERSION
```

There's no `tarballs` directory as I have if I run locally. Does this give any info about the issue?

I'm cloning master branch from edip.

**Comment by asaaki** [comment]
Well, it seems that the volume mounting is not working correctly/at all.

Could you check with a simpler setup maybe?
Use something like busybox image:

``` shell
docker run --rm -ti -v `pwd`:/world busybox /bin/touch /world/file-should-land-on-host
```

In the directory where this command was triggered a `file-should-land-on-host` should have been created. (You can replace `pwd` with `$(pwd)` or a manually set absolute path, too. But this should not make any difference.)

If this is not the case then something is definitely odd with your docker setup on your CI server.

And if I understand correctly all this stuff already runs within another docker container?
(I'm a bit lost now of how many nested levels of containers we are talking. :sweat_smile:)

**Comment by edgurgel** [comment]
Ok I think I understand the problem now (or partially).

Drone runs a container that will run the tests and then the whole edip process. I will call this `ci-container`

I'm pointing to the outside docker host as the `ci-container` does not have a docker daemon. The mounted volumes end up being available outside of the `ci-container` and for this reason I can't see the tarballs. I mounted the volume on a directory that Drone won't clean and I found the tarballs sitting there. They are not available for the `ci-container` because the volumes are outside. 

So a solution would be to run a docker daemon inside the `ci-container` ? I will try that in the meanwhile.

Does this make any sense? :laughing:

**Comment by edgurgel** [comment]
Or I may try something like [wrapdocker](https://github.com/jpetazzo/dind)..

**Comment by edgurgel** [comment]
Ok doing this after generating the tarball worked:

```
docker run --rm -v `pwd`:/edip busybox cat /edip/tarballs/hello-0.0.1.tar.gz | docker import - local:hello
```

It feels gross as it abuses docker run to access the mounted volume so I will probably try another solution.

I think we can close the issue as it doesn't seem to be a problem with edip but with my building process. I really don't know if something could be changed to help me.

Feel free to close! Thanks for the help :+1:

**Comment by asaaki** [comment]
I wish I could have helped much more.

Feel free to give feedback if you achieved a better solution. I guess we all can only benefit from it.
I'm also reachable via [Twitter](https://twitter.com/asaaki), the [Elixir Slack](https://elixir-lang.slack.com), or even now on IRC (freenode #elixir-lang).

**Comment by asaaki** [comment]
Oh, totally overlooked your _ci-container_ stuff.

You should check if you can run this ci-container with `--privileged` and `-v <docker socket mapping> -v <docker executable mapping>` (like [described above](https://github.com/asaaki/elixir-docker-image-packager/issues/4#issuecomment-128349946) from the EDIP Makefile). This should make a lot of things easier.

**Comment by edgurgel** [comment]
I ended up using the image  edip-tool:3.0 as base image and simply linked my source to /source then ran `make` using the Makefile provided by edip-tool. I had to do the docker import by myself, but I imagine it wouldn't be too hard to add a target to the Makefile so it would use the artifact.cfg to run docker import. 

Thanks again for this awesome project!

**Comment by asaaki** [comment]
I've ditched the Makefile approach for the sake of the mix task.
But I can readd one again for the folks interested in it.
Current README.md describes the basic steps, so it should not be so difficult.
(The `artifact.cfg` is pretty simple to parse with tools like _sed_.)

**Comment by edgurgel** [comment]
I will parse the `artifact.cfg` file for now. I think it's alright :+1:
